name:     Airplay2 Multiroom Audio
version: "0.39"
slug:     airplay2_multiroom_audio
description: Create AirPlay 2 receivers from local audio devices, one per pulseaudio physical remap sink output. Remap sinks with automatic or custom names can be created in the Multi-Room Audio Controlle Home Assistand app.
arch:
  - amd64
  - aarch64
map:
  - addon_config:rw
  - media:rw
host_network: true
audio: true
init: false
startup: services
boot: auto
backup: hot
stage: experimental
